package TestCases;

import Object_Repository.Mint_activations_Page;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class Mint_activations_Test {
	public WebDriver driver;
	public WebDriverWait wait;
	Mint_activations_Page hpp = new Mint_activations_Page(driver);


	  @BeforeMethod
	  public void setUp() {
		  System.setProperty("webdriver.chrome.driver", "//usr/local/bin/chromedriver");
		  driver = new ChromeDriver();
		  wait = new WebDriverWait(driver,10);
		  
	  }
  

	 @Test(priority=1)
	 public void mintActivate_12MoLarge()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_12MoLarge_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_12MoLarge_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
// }		  

//		  if(driver.findElement(By.xpath("//h1[contains(text(),'Activation In Progress')]")) != null){
//			  Thread.sleep(60000);
//			  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
//		  }
//		  if(driver.findElement(By.xpath("//h1[contains(text(),'Activation Complete')]")) != null){
//			  String ActivationCompleteText1 = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
//			  Assert.assertEquals(ActivationCompleteText1, "Activation Complete");
//		  }
//	 }  
 
	  
	 }

	 @Test(priority=-1)
	 public void mintActivate_12MoMedium()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_12MoMedium_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_12MoMedium_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 }	  
	  
	 @Test(priority=3)
	 public void mintActivate_12MoSmall()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_12MoSmall_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_12MoSmall_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 }  
	 
	 @Test(priority=4)
	 public void mintActivate_3MoLarge()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_3MoLarge_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_3MoLarge_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 }  
	 @Test(priority=2)
	 public void mintActivate_3MoMedium()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_3MoMedium_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_3MoMedium_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 }  
	 
	 @Test(priority=6)
	 public void mintActivate_3MoSmall()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_3MoSmall_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_3MoSmall_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 }  
	 
	 @Test(priority=7)
	 public void mintActivate_6MoLarge()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_6MoLarge_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_6MoLarge_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 }  

	 @Test(priority=8)
	 public void mintActivate_6MoMedium()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_6MoMedium_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_6MoMedium_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 } 
	 @Test(priority=9)
	 public void mintActivate_6MoSmall()throws InterruptedException {
		  driver.get("https://www.slack.com");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_button_SignIn())).click();
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_workpace_URL())).sendKeys("ultramobile" + Keys.RETURN); 
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_email_Address())).sendKeys("qatester@ultra.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_password())).sendKeys("UltraMobile#1" + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.slack_textbox())).sendKeys("/geticcid" + Keys.RETURN + Keys.RETURN);
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_SelectSimStatus())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Available())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_OrangeSim())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_Brand())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_AUTOMATIONMint())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductType())).click();
		  Thread.sleep(3000);
		  Actions action = new Actions(driver);
		  WebElement we = driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"));
		  action.moveToElement(we).moveToElement(driver.findElement(By.xpath("//span[contains(text(),'12 Month Medium')]"))).build().perform();
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  action.sendKeys(Keys.ARROW_DOWN);
		  action.sendKeys(Keys.ARROW_DOWN);
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.elementToBeClickable(hpp.getICCID_6MoSmall_Type())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_InitialProductID())).click();
		  Thread.sleep(3000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_6MoSmall_ID())).click();
		   Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_button_GetICCID())).click();
		  Thread.sleep(3000);
		 String CopyActCode =  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.getICCID_textbox_GetACTCODE())).getText();
		 driver.manage().deleteAllCookies();
		  Thread.sleep(3000);
		  driver.get("https://www.mintmobile.com");	
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintHeader_button_Activate())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_textbox_ActCode())).sendKeys(CopyActCode);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mint_button_StartActivation())).click();
		  Thread.sleep(2000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_InputZipCode())).sendKeys("92626");
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_ActivateaNewNumber())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_Checkbox())).click();
		  Thread.sleep(1000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.signActivation_button_ProceedActivation())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CreditCard())).sendKeys("4111 1111 1111 1111");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_CVV())).sendKeys("123");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ExpDate())).sendKeys("01/30");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address())).sendKeys("1550 Scenic Ave");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Address2())).sendKeys("Suite 100");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_City())).sendKeys("Costa Mesa");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_State())).sendKeys("CA");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ZipCode())).sendKeys("92626");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  Thread.sleep(5000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_FirstName())).sendKeys("Mint");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_LastName())).sendKeys("Mobile");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Email())).sendKeys("noemail@mint.me");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_Password())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_textbox_ConfirmPassword())).sendKeys("Testing1!");
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_SubmitInfo())).click();
		  Thread.sleep(60000);
		  wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_button_submit())).click();
		  String ActivationCompleteText = wait.until(ExpectedConditions.visibilityOfElementLocated(hpp.mintActivation_text_Complete())).getText();
		  Assert.assertEquals(ActivationCompleteText, "Activation Complete");
 } 

  @AfterMethod
  public void tearDown() {
		driver.quit();
  }

}
